/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:421237b2-811e-4692-a0fd-1b60bceee1c3",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_N98Y1zw3v",
    "aws_user_pools_web_client_id": "388mnkrc9p04bq06s7q1it06t2",
    "oauth": {},
    
};


export default awsmobile;
